name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        cd backend
        npm ci

    - name: Run Tests
      run: |
        cd backend
        npm test

    - name: Build and Push Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd backend
        docker build -t $DOCKER_USERNAME/test-platform-backend:latest .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_USERNAME/test-platform-backend:latest

    - name: Trigger Jenkins Build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        curl -X POST \
          -u ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }} \
          ${{ secrets.JENKINS_URL }}/job/test-platform-deploy/build